# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import task_pb2 as task__pb2


class TaskapiStub(object):
    """Task service API 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addClient = channel.unary_unary(
                '/Taskapi/addClient',
                request_serializer=task__pb2.ClientDetails.SerializeToString,
                response_deserializer=task__pb2.Id.FromString,
                )
        self.delClient = channel.unary_unary(
                '/Taskapi/delClient',
                request_serializer=task__pb2.Id.SerializeToString,
                response_deserializer=task__pb2.Client.FromString,
                )
        self.listClients = channel.unary_unary(
                '/Taskapi/listClients',
                request_serializer=task__pb2.Empty.SerializeToString,
                response_deserializer=task__pb2.Clients.FromString,
                )


class TaskapiServicer(object):
    """Task service API 
    """

    def addClient(self, request, context):
        """Add a new task and return its id 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delClient(self, request, context):
        """Delete a task by id 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listClients(self, request, context):
        """List all tasks 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskapiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addClient': grpc.unary_unary_rpc_method_handler(
                    servicer.addClient,
                    request_deserializer=task__pb2.ClientDetails.FromString,
                    response_serializer=task__pb2.Id.SerializeToString,
            ),
            'delClient': grpc.unary_unary_rpc_method_handler(
                    servicer.delClient,
                    request_deserializer=task__pb2.Id.FromString,
                    response_serializer=task__pb2.Client.SerializeToString,
            ),
            'listClients': grpc.unary_unary_rpc_method_handler(
                    servicer.listClients,
                    request_deserializer=task__pb2.Empty.FromString,
                    response_serializer=task__pb2.Clients.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Taskapi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Taskapi(object):
    """Task service API 
    """

    @staticmethod
    def addClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Taskapi/addClient',
            task__pb2.ClientDetails.SerializeToString,
            task__pb2.Id.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Taskapi/delClient',
            task__pb2.Id.SerializeToString,
            task__pb2.Client.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Taskapi/listClients',
            task__pb2.Empty.SerializeToString,
            task__pb2.Clients.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
